spring:
  profiles:
    include: common
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:oracle:thin:아이피:포트:데이터베이스명
    username:
    password:
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 60000
      max-lifetime: 1800000
logging:
  config: classpath:log4j2-dr.xml

---

#common

spring:
  config:
    activate:
      on-profile: common
  transaction:
    default-timeout: 10s
  datasource:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 3000
      validation-timeout: 5000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    show-sql: false
    properties:
      jdbc:
        non_contextual_creation: true